[package]
name = "raft-memcached"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memcache = "*"
rand = "*"
async-raft = "*"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"